-- Foundation Level 1 "Ordinary Thinking" MCQ bank (53 rows)
CREATE TABLE IF NOT EXISTS public.foundation_questions (
  id SERIAL PRIMARY KEY,
  unit TEXT NOT NULL,
  topic TEXT NOT NULL,
  exam_style TEXT,
  difficulty TEXT,
  level INT NOT NULL DEFAULT 1,
  section TEXT NOT NULL DEFAULT 'Ordinary Thinking',
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  correct TEXT NOT NULL,
  explanation TEXT,
  formula TEXT
);

CREATE INDEX IF NOT EXISTS idx_foundation_questions_unit_topic
  ON public.foundation_questions (unit, topic, level, section);

ALTER TABLE public.foundation_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read foundation_questions" ON public.foundation_questions;
CREATE POLICY "Allow read foundation_questions"
  ON public.foundation_questions FOR SELECT
  USING (true);

GRANT SELECT ON public.foundation_questions TO anon, authenticated, service_role;

INSERT INTO public.foundation_questions (unit, topic, exam_style, difficulty, level, section, question, options, correct, explanation, formula)
VALUES
('Kinematics', 'Distance and Displacement', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A boy walks 4 m towards east, then 3 m towards north. What is his resultant displacement from the starting point?', '["(a) 7 m","(b) 5 m","(c) 1 m","(d) 12 m"]'::jsonb, '2', 'Using Pythagoras theorem: displacement = √(4² + 3²) = √(16 + 9) = √25 = 5 m', 'd = √(x² + y²)'),
('Kinematics', 'Distance and Displacement', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A person travels 12 m towards east and then 5 m towards south. The distance and displacement of the person are respectively:', '["(a) 17 m and 7 m","(b) 13 m and 17 m","(c) 17 m and 13 m","(d) 7 m and 13 m"]'::jsonb, '3', 'Distance = 12 + 5 = 17 m. Displacement = √(12² + 5²) = √(144 + 25) = √169 = 13 m', 'Distance = sum of all paths, Displacement = √(x² + y²)'),
('Kinematics', 'Distance and Displacement', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A car travels from A to B, a distance of 100 km. It then returns from B to A. The total distance and displacement are:', '["(a) 200 km and 200 km","(b) 100 km and 0","(c) 200 km and 0","(d) 0 and 200 km"]'::jsonb, '3', 'Total distance = 100 + 100 = 200 km. Since start and end points are same, displacement = 0', 'Displacement = final position - initial position'),
('Kinematics', 'Average Speed and Average Velocity', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A car covers first half of distance between two places at 40 km/h and second half at 60 km/h. The average speed of the car is:', '["(a) 50 km/h","(b) 48 km/h","(c) 45 km/h","(d) 55 km/h"]'::jsonb, '2', 'For equal distances: avg speed = 2v1v2/(v1+v2) = 2×40×60/(40+60) = 4800/100 = 48 km/h', 'avg speed = 2v1v2/(v1+v2)'),
('Kinematics', 'Average Speed and Average Velocity', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A man walks 20 m in 4 seconds and then 10 m in the opposite direction in 2 seconds. His average speed and average velocity are:', '["(a) 5 m/s and 5/3 m/s","(b) 5 m/s and 5 m/s","(c) 5/3 m/s and 5 m/s","(d) 3 m/s and 5/3 m/s"]'::jsonb, '1', 'Total distance = 20+10 = 30m, Total time = 6s. Speed = 30/6 = 5 m/s. Net displacement = 20-10 = 10m. Velocity = 10/6 = 5/3 m/s', 'avg speed = total distance/total time, avg velocity = displacement/time'),
('Kinematics', 'Kinematic Equations of Motion', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A train starts from rest and accelerates uniformly at 2 m/s². The velocity of the train after 10 seconds is:', '["(a) 10 m/s","(b) 15 m/s","(c) 20 m/s","(d) 25 m/s"]'::jsonb, '3', 'Using v = u + at: v = 0 + 2×10 = 20 m/s', 'v = u + at'),
('Kinematics', 'Kinematic Equations of Motion', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A car moving at 72 km/h is brought to rest by applying brakes. If the deceleration is 5 m/s², the distance covered before stopping is:', '["(a) 20 m","(b) 40 m","(c) 30 m","(d) 50 m"]'::jsonb, '2', 'u = 72 km/h = 20 m/s, v = 0. Using v² = u² - 2as: 0 = 400 - 2×5×s, s = 400/10 = 40 m', 'v² = u² + 2as'),
('Kinematics', 'Kinematic Equations of Motion', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A body starts from rest and travels for 5 seconds with uniform acceleration of 4 m/s². The distance covered in the 5th second is:', '["(a) 18 m","(b) 16 m","(c) 20 m","(d) 22 m"]'::jsonb, '1', 'Distance in nth second: Sn = u + a(2n-1)/2 = 0 + 4×(2×5-1)/2 = 4×9/2 = 18 m', 'Sₙ = u + a(2n-1)/2'),
('Kinematics', 'Free Fall', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A stone is dropped from a height of 80 m. The time taken to reach the ground is (g = 10 m/s²):', '["(a) 2 s","(b) 3 s","(c) 4 s","(d) 5 s"]'::jsonb, '3', 'h = ½gt²: 80 = ½×10×t², t² = 16, t = 4 s', 'h = ½gt²'),
('Kinematics', 'Free Fall', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A ball is thrown vertically upward with a velocity of 20 m/s. The maximum height reached is (g = 10 m/s²):', '["(a) 10 m","(b) 20 m","(c) 30 m","(d) 40 m"]'::jsonb, '2', 'Using v² = u² - 2gh at max height v=0: 0 = 400 - 2×10×h, h = 400/20 = 20 m', 'v² = u² - 2gh'),
('Laws of Motion', 'Newton''s Second Law (F=ma)', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A force of 50 N acts on a body of mass 10 kg initially at rest. The acceleration produced is:', '["(a) 3 m/s²","(b) 4 m/s²","(c) 5 m/s²","(d) 6 m/s²"]'::jsonb, '3', 'F = ma, a = F/m = 50/10 = 5 m/s²', 'F = ma'),
('Laws of Motion', 'Newton''s Second Law (F=ma)', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A body of mass 5 kg is acted upon by two perpendicular forces 8 N and 6 N. The acceleration of the body is:', '["(a) 1 m/s²","(b) 2 m/s²","(c) 3 m/s²","(d) 4 m/s²"]'::jsonb, '2', 'Net force = √(8² + 6²) = √(64+36) = √100 = 10 N. a = F/m = 10/5 = 2 m/s²', 'F_net = √(F1² + F2²), a = F/m'),
('Laws of Motion', 'Newton''s Third Law of Motion', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A rifle of mass 4 kg fires a bullet of mass 50 g with a velocity of 400 m/s. The recoil velocity of the rifle is:', '["(a) 3 m/s","(b) 4 m/s","(c) 5 m/s","(d) 6 m/s"]'::jsonb, '3', 'By conservation of momentum: 0 = m₁v₁ + m₂v₂. 4×v = 0.05×400, v = 20/4 = 5 m/s', 'm₁v₁ = m₂v₂ (conservation of momentum)'),
('Laws of Motion', 'Impulse-Momentum Principle', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A cricket ball of mass 0.15 kg moving at 20 m/s is stopped by a player in 0.05 s. The force exerted by the player is:', '["(a) 30 N","(b) 40 N","(c) 50 N","(d) 60 N"]'::jsonb, '4', 'Impulse = change in momentum. F×t = m×(v-u). F×0.05 = 0.15×(20-0) = 3. F = 3/0.05 = 60 N', 'F = m(v-u)/t'),
('Laws of Motion', 'Free Body Diagrams', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A block of mass 10 kg is placed on a frictionless surface. A horizontal force of 30 N is applied. The normal reaction of the surface on the block is (g = 10 m/s²):', '["(a) 30 N","(b) 50 N","(c) 80 N","(d) 100 N"]'::jsonb, '4', 'The normal reaction balances the weight of the block. N = mg = 10×10 = 100 N. Horizontal force does not affect normal reaction on flat surface.', 'N = mg (on horizontal surface)'),
('Work, Energy and Power', 'Work Done by a Force', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A force of 20 N acts on a body and displaces it by 5 m in the direction of the force. The work done is:', '["(a) 4 J","(b) 10 J","(c) 25 J","(d) 100 J"]'::jsonb, '4', 'W = F × d × cos θ = 20 × 5 × cos 0° = 100 J', 'W = Fd cosθ'),
('Work, Energy and Power', 'Kinetic and Potential Energy', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A body of mass 2 kg is moving with a velocity of 10 m/s. Its kinetic energy is:', '["(a) 10 J","(b) 20 J","(c) 100 J","(d) 200 J"]'::jsonb, '3', 'KE = ½mv² = ½ × 2 × 10² = ½ × 2 × 100 = 100 J', 'KE = ½mv²'),
('Work, Energy and Power', 'Kinetic and Potential Energy', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A stone of mass 2 kg is at a height of 5 m above the ground. Its potential energy is (g = 10 m/s²):', '["(a) 10 J","(b) 50 J","(c) 100 J","(d) 200 J"]'::jsonb, '3', 'PE = mgh = 2 × 10 × 5 = 100 J', 'PE = mgh'),
('Work, Energy and Power', 'Conservation of Energy', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A ball of mass 1 kg is dropped from a height of 20 m. Just before hitting the ground its velocity is (g = 10 m/s²):', '["(a) 10 m/s","(b) 15 m/s","(c) 20 m/s","(d) 25 m/s"]'::jsonb, '3', 'By conservation of energy: mgh = ½mv², v = √(2gh) = √(2×10×20) = √400 = 20 m/s', 'v = √(2gh)'),
('Work, Energy and Power', 'Power and Its Units', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A machine does 1000 J of work in 10 seconds. Its power is:', '["(a) 10 W","(b) 100 W","(c) 1000 W","(d) 10000 W"]'::jsonb, '2', 'P = W/t = 1000/10 = 100 W', 'P = W/t'),
('Gravitation', 'Newton''s Law of Gravitation', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The gravitational force between two bodies is F. If the distance between them is doubled, the new force will be:', '["(a) 4F","(b) 2F","(c) F/2","(d) F/4"]'::jsonb, '4', 'F ∝ 1/r². If r becomes 2r, F becomes F/(2)² = F/4', 'F = Gm₁m₂/r²'),
('Gravitation', 'Newton''s Law of Gravitation', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'The gravitational force between two objects is 100 N. If the mass of one object is doubled and distance is halved, the new force is:', '["(a) 200 N","(b) 400 N","(c) 800 N","(d) 50 N"]'::jsonb, '3', 'F'' = G(2m₁)m₂/(r/2)² = G(2m₁m₂)×4/r² = 8F = 8×100 = 800 N', 'F = Gm₁m₂/r²'),
('Gravitation', 'Acceleration Due to Gravity', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The weight of a body on the surface of the earth is 600 N. At a height equal to radius of earth, the weight becomes:', '["(a) 600 N","(b) 300 N","(c) 200 N","(d) 150 N"]'::jsonb, '4', 'At height h=R: g'' = g/(1+h/R)² = g/(1+1)² = g/4. Weight = 600/4 = 150 N', 'g'' = g(R/(R+h))²'),
('Gravitation', 'Escape Velocity and Orbital Velocity', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The escape velocity from the surface of the earth is 11.2 km/s. The escape velocity from a planet with same mass but double the radius is:', '["(a) 22.4 km/s","(b) 11.2 km/s","(c) 5.6√2 km/s","(d) 7.92 km/s"]'::jsonb, '4', 've = √(2GM/R). If R doubles: ve'' = √(2GM/2R) = ve/√2 = 11.2/√2 ≈ 7.92 km/s', 've = √(2GM/R)'),
('Gravitation', 'Kepler''s Laws', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The period of revolution of a planet around the sun is 8 years. The ratio of its orbital radius to Earth''s orbital radius is:', '["(a) 2","(b) 4","(c) 8","(d) 16"]'::jsonb, '2', 'By Kepler''s 3rd law: T² ∝ R³. (T/Te)² = (R/Re)³. (8/1)² = (R/Re)³. R/Re = (64)^(1/3) = 4', 'T² ∝ R³'),
('Properties of Matter', 'Hooke''s Law', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A spring has a spring constant of 200 N/m. What force is required to extend it by 5 cm?', '["(a) 5 N","(b) 10 N","(c) 15 N","(d) 40 N"]'::jsonb, '2', 'F = kx = 200 × 0.05 = 10 N', 'F = kx'),
('Properties of Matter', 'Young''s Modulus', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A wire of length 2 m is stretched by 1 mm by a force. If the Young''s modulus is 2×10¹¹ Pa and area is 10⁻⁶ m², the force applied is:', '["(a) 100 N","(b) 1000 N","(c) 10000 N","(d) 100000 N"]'::jsonb, '1', 'Y = FL/AΔL. F = YAΔl/L = (2×10¹¹ × 10⁻⁶ × 10⁻³)/2 = 100 N', 'Y = (F/A)/(ΔL/L)'),
('Properties of Matter', 'Pressure and Its Measurement', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'The pressure at a depth of 10 m below the surface of water is (ρ = 1000 kg/m³, g = 10 m/s²):', '["(a) 1×10⁵ Pa","(b) 1×10⁵ Pa (gauge)","(c) 2×10⁵ Pa","(d) 0.1×10⁵ Pa"]'::jsonb, '3', 'P = P₀ + ρgh = 10⁵ + 1000×10×10 = 10⁵ + 10⁵ = 2×10⁵ Pa', 'P = P₀ + ρgh'),
('Thermodynamics', 'Gas Equation', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A gas occupies 2 L at 300 K. At constant pressure, the volume at 600 K will be:', '["(a) 1 L","(b) 2 L","(c) 4 L","(d) 8 L"]'::jsonb, '3', 'At constant pressure: V₁/T₁ = V₂/T₂. V₂ = V₁T₂/T₁ = 2×600/300 = 4 L', 'V₁/T₁ = V₂/T₂ (Charles''s Law)'),
('Thermodynamics', 'Gas Equation', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A gas at 27°C has pressure P₀. At constant volume, the pressure at 127°C is:', '["(a) 4P₀/3","(b) 3P₀/4","(c) 2P₀/3","(d) 3P₀/2"]'::jsonb, '1', 'P₁/T₁ = P₂/T₂. P₂ = P₀ × 400/300 = 4P₀/3. (T in Kelvin: 27°C = 300K, 127°C = 400K)', 'P₁/T₁ = P₂/T₂ (Gay-Lussac''s Law)'),
('Oscillations', 'Simple Harmonic Motion', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The time period of a simple pendulum of length 1 m is (g = 10 m/s², π² = 10):', '["(a) 1 s","(b) 2 s","(c) 3 s","(d) 4 s"]'::jsonb, '2', 'T = 2π√(L/g) = 2π√(1/10) = 2π/√10 ≈ 2×π/π = 2 s (using π² = 10)', 'T = 2π√(L/g)'),
('Oscillations', 'Time Period and Frequency', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A body executing SHM has a time period of 0.2 s. Its frequency is:', '["(a) 2 Hz","(b) 4 Hz","(c) 5 Hz","(d) 10 Hz"]'::jsonb, '3', 'f = 1/T = 1/0.2 = 5 Hz', 'f = 1/T'),
('Oscillations', 'Simple Pendulum', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'The time period of a pendulum on the moon is 4.9 s. If g on moon is g/6 where g = 9.8 m/s², what is the length of pendulum? (π² = 10)', '["(a) 1 m","(b) 2 m","(c) 3 m","(d) 4 m"]'::jsonb, '2', 'T = 2π√(L/g_moon). g_moon = 9.8/6 ≈ 1.63 m/s². L = T²g/(4π²) = 4.9²×1.63/40 ≈ 2 m', 'T = 2π√(L/g)'),
('Electrostatics', 'Coulomb''s Law', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'Two charges each of 1 μC are placed 1 m apart. The force between them is (k = 9×10⁹ Nm²/C²):', '["(a) 9×10⁻³ N","(b) 9×10⁻² N","(c) 9×10⁻¹ N","(d) 9 N"]'::jsonb, '1', 'F = kq₁q₂/r² = 9×10⁹ × 10⁻⁶ × 10⁻⁶/1² = 9×10⁻³ N', 'F = kq₁q₂/r²'),
('Electrostatics', 'Coulomb''s Law', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'The force between two charges is F. If each charge is doubled and distance is also doubled, the new force is:', '["(a) F","(b) 2F","(c) F/2","(d) 4F"]'::jsonb, '1', 'F'' = k(2q₁)(2q₂)/(2r)² = k×4q₁q₂/4r² = kq₁q₂/r² = F', 'F = kq₁q₂/r²'),
('Electrostatics', 'Electric Field', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A charge of 2 μC is placed in an electric field of 3×10⁵ N/C. The force on the charge is:', '["(a) 0.3 N","(b) 0.6 N","(c) 1.5 N","(d) 6 N"]'::jsonb, '2', 'F = qE = 2×10⁻⁶ × 3×10⁵ = 6×10⁻¹ = 0.6 N', 'F = qE'),
('Current Electricity', 'Ohm''s Law', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A potential difference of 12 V is applied across a resistor of 4 Ω. The current through the resistor is:', '["(a) 1 A","(b) 2 A","(c) 3 A","(d) 4 A"]'::jsonb, '3', 'I = V/R = 12/4 = 3 A', 'V = IR (Ohm''s Law)'),
('Current Electricity', 'Resistance', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'Three resistors of 2 Ω, 3 Ω and 6 Ω are connected in parallel. The equivalent resistance is:', '["(a) 11 Ω","(b) 1 Ω","(c) 2 Ω","(d) 3 Ω"]'::jsonb, '2', '1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1. R = 1 Ω', '1/R = 1/R₁ + 1/R₂ + 1/R₃'),
('Current Electricity', 'Resistors in Series and Parallel', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'Two resistors of 4 Ω and 6 Ω are connected in series to a 20 V battery. The current in the circuit is:', '["(a) 1 A","(b) 2 A","(c) 3 A","(d) 4 A"]'::jsonb, '2', 'R_total = 4 + 6 = 10 Ω. I = V/R = 20/10 = 2 A', 'R_series = R₁ + R₂, I = V/R'),
('Dual Nature, Atoms & Nuclei', 'Photoelectric Effect', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The work function of a metal is 2 eV. The minimum frequency of light needed to emit electrons is (h = 6.6×10⁻³⁴ Js, 1 eV = 1.6×10⁻¹⁹ J):', '["(a) 4.8×10¹⁴ Hz","(b) 5.8×10¹⁴ Hz","(c) 6.8×10¹⁴ Hz","(d) 7.8×10¹⁴ Hz"]'::jsonb, '1', 'φ = hν₀. ν₀ = φ/h = (2×1.6×10⁻¹⁹)/(6.6×10⁻³⁴) = 4.8×10¹⁴ Hz', 'φ = hν₀ (threshold frequency)'),
('Dual Nature, Atoms & Nuclei', 'Bohr''s Atomic Model', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'The radius of the first Bohr orbit of hydrogen is 0.53 Å. The radius of the third orbit is:', '["(a) 1.59 Å","(b) 4.77 Å","(c) 9 Å","(d) 0.59 Å"]'::jsonb, '2', 'rₙ = n²r₁ = 3² × 0.53 = 9 × 0.53 = 4.77 Å', 'rₙ = n²r₁'),
('Optics', 'Reflection and Spherical Mirrors', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'An object is placed 20 cm in front of a concave mirror of focal length 10 cm. The image distance is:', '["(a) -10 cm","(b) -20 cm","(c) -30 cm","(d) -40 cm"]'::jsonb, '2', 'Using mirror formula: 1/v + 1/u = 1/f. 1/v + 1/(-20) = 1/(-10). 1/v = -1/10 + 1/20 = -1/20. v = -20 cm', '1/v + 1/u = 1/f'),
('Optics', 'Refraction at Plane and Spherical Surfaces', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'For a ray going from water (n = 4/3) to glass (n = 3/2), the critical angle for total internal reflection at the water–glass interface (glass is optically denser) is:', '["(a) sin⁻¹(8/9)","(b) sin⁻¹(9/8)","(c) sin⁻¹(2/3)","(d) sin⁻¹(3/2)"]'::jsonb, '1', 'Light must travel from the denser medium toward the rarer medium for TIR at that boundary. From glass to water: sin C = n_water/n_glass = (4/3)/(3/2) = 8/9, so C = sin⁻¹(8/9).', 'sin(C) = n_rarer/n_denser'),
('Optics', 'Total Internal Reflection', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The critical angle for total internal reflection in glass (n = 1.5) with respect to air is:', '["(a) 30°","(b) 41.8°","(c) 45°","(d) 60°"]'::jsonb, '2', 'sin(C) = 1/n = 1/1.5 = 2/3. C = sin⁻¹(2/3) ≈ 41.8°', 'sin(C) = 1/n'),
('Rotational Motion', 'Moment of Force and Torque', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A force of 10 N is applied at a distance of 0.5 m from the pivot. The torque produced is:', '["(a) 2.5 Nm","(b) 5 Nm","(c) 10 Nm","(d) 20 Nm"]'::jsonb, '2', 'τ = F × r × sin90° = 10 × 0.5 = 5 Nm', 'τ = F × r × sinθ'),
('Rotational Motion', 'Angular Momentum', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A particle of mass 0.5 kg moves in a circle of radius 2 m with a speed of 4 m/s. Its angular momentum is:', '["(a) 2 kg m²/s","(b) 4 kg m²/s","(c) 8 kg m²/s","(d) 16 kg m²/s"]'::jsonb, '2', 'L = mvr = 0.5 × 4 × 2 = 4 kg m²/s', 'L = mvr'),
('Units & Measurements', 'Dimensional Analysis', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The dimensional formula of force is:', '["(a) [MLT⁻¹]","(b) [MLT⁻²]","(c) [ML²T⁻²]","(d) [ML⁻¹T⁻²]"]'::jsonb, '2', 'F = ma. [F] = [M][LT⁻²] = [MLT⁻²]', 'F = ma → [MLT⁻²]'),
('Units & Measurements', 'Dimensional Analysis', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'Which of the following has the same dimensional formula as energy?', '["(a) Force","(b) Power","(c) Torque","(d) Impulse"]'::jsonb, '3', 'Energy = [ML²T⁻²]. Torque = F×r = [MLT⁻²][L] = [ML²T⁻²]. Same dimensional formula!', 'Energy and Torque both = [ML²T⁻²]'),
('Units & Measurements', 'Fundamental and Derived Quantities', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'Which of the following is a fundamental quantity?', '["(a) Velocity","(b) Force","(c) Electric current","(d) Pressure"]'::jsonb, '3', 'Fundamental quantities are: length, mass, time, electric current, temperature, luminous intensity, amount of substance. Electric current (Ampere) is fundamental. Others are derived.', '7 fundamental quantities in SI system'),
('Kinematics', 'Velocity-Time Graphs', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'In a velocity-time graph, the area under the curve represents:', '["(a) Acceleration","(b) Force","(c) Distance covered","(d) Power"]'::jsonb, '3', 'Area under v-t graph = ∫v dt = displacement/distance covered', 'Area under v-t graph = displacement'),
('Kinematics', 'Acceleration', 'NEET', 'Easy', 1, 'Ordinary Thinking', 'A body moving with uniform velocity has acceleration:', '["(a) Positive","(b) Negative","(c) Zero","(d) Variable"]'::jsonb, '3', 'Uniform velocity means constant speed in constant direction. No change in velocity means acceleration = 0', 'a = dv/dt = 0 for uniform velocity'),
('Laws of Motion', 'Newton''s First Law of Motion', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'A book lying on a table remains at rest. This is an example of:', '["(a) Newton''s Second Law","(b) Newton''s Third Law","(c) Newton''s First Law","(d) Law of conservation of momentum"]'::jsonb, '3', 'A body at rest continues to remain at rest unless acted upon by external force — this is Newton''s First Law (Law of Inertia)', 'Newton''s First Law: F = 0 → a = 0'),
('Work, Energy and Power', 'Area Under Force-Displacement Graph', 'JEE', 'Easy', 1, 'Ordinary Thinking', 'The area under a force-displacement graph gives:', '["(a) Power","(b) Impulse","(c) Work done","(d) Kinetic energy"]'::jsonb, '3', 'W = ∫F.dx = Area under F-x graph', 'W = ∫F dx = area under F-x graph');
